# SPDX-FileCopyrightText: 2021 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: MIT

name: CI

on:
  pull_request:
  push:
    paths-ignore:
      - 'AUTHORS'
      - 'LICENSE'
      - 'NOTICE'
      - '**.md'
      - '.gitignore'
    tags-ignore:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    branches:
      - main
  schedule:
    - cron: '12 9 * * 3'

jobs:
  test:
  - uses: actions/checkout@v2
    with:
      fetch-depth: 0

  - name: Start Autobahn Docker
    run: |
      docker run --rm -v "$GITHUB_WORKSPACE/tools:/config" -v "$GITHUB_WORKSPACE/reports:/reports" -p 9001:9001 --name fuzzingserver crossbario/autobahn-testsuite &

  - uses: xmidt-org/.github/.github/workflows/meson-unit-test.yml@main
    with:
      packages: jq libcurl4-openssl-dev
      extra-checks: autobahn_collect autobahn_validate
    secrets:
      sonar_login: ${{ secrets.SONAR_TOKEN }}
